### ISSUE TITLE
Unable to install via composer

### ISSUE THREAD

**Issue by pjmil** [fourstacks/nova-repeatable-fields#1]
```
[InvalidArgumentException]
  Could not find a version of package fourstacks/nova-repeatable-fields matching your m
  inimum-stability (dev). Require it with an explicit version constraint allowing its d
  esired stability.
```

**Comment by fourstacks** [comment]
Hi @pjmil - could you tell me how you are installing the package?  Did you `composer require fourstacks/nova-repeatable-fields`,  or did you manually add it to your composer.json file with a version?

**Comment by fourstacks** [comment]
@pjmil - I've just tagged a v0.1.0 release which hopefully might fix the issue you're having.  If you could try pulling in the latest version and let me know if that solves the problem for you that would be great

**Comment by hariesnurikhwan** [comment]
Hi, I'm getting the same issue. I've tried running `composer require fourstacks/nova-repeatable-fields` and manually add to composer.json.


```
 Problem 1
    - The requested package fourstacks/nova-repeatable-fields could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
```

**Comment by fourstacks** [comment]
Hi @hariesnurikhwan - looks like this is a different error to the OP juding by the error.

Could you take a look at your composer.json file and see what you have set for `minimum-stability`?  It should be 'dev by default in a Laravel project I think

There is a stable release tagged in packagist so I'm at a bit of a loss to figure out why this isn't installing for you.  Perhaps make sure that if you have manually added the package in your composer.json that you are targetting the 0.1.0 version?

**Comment by hariesnurikhwan** [comment]
I did set `minimum-stability` to `dev` but for unknown reason it didn't found. I did try again just now and it suddenly works lol.

But anyway thanks for your package 👍

**Comment by fourstacks** [comment]
Glad you got it up and running @hariesnurikhwan 👍  

Will close this now.
