### ISSUE TITLE
Field order incorrect in Detail view

### ISSUE THREAD

**Issue by tanthammar** [fourstacks/nova-repeatable-fields#11]
I've set up my field like this:
Repeater::make('Addresses', 'addresses')
            ->addField([
                'label' => 'Label',
                'name' => 'label',
                'placeholder' => 'Label/Department',
                'type' => 'text'
            ])
            ->addField([
                'label' => 'Street',
                'name' => 'street',
                'type' => 'text'
            ])
            ->addField([
                'label' => 'Zip',
                'name' => 'zip',
                'type' => 'text'
            ])
            ->addField([
                'label' => 'City',
                'name' => 'city',
                'type' => 'text'
            ])
            ->addField([
                'label' => 'Country',
                'name' => 'country',
                'type' => 'text'
            ])
            ->addButtonText('Add Address')
            ->summaryLabel('Addresses')
            ->hideFromIndex()
            ,

But in Detail view the fields are in a strange order
Zip:
City:
Label:
Street:
Country:

**Comment by fourstacks** [comment]
Hi @tanthammar - sorry for slow reply and thanks for the bug report.  I'll see if I can replicate this and get back to you.  Can't see a good reason off the top of my head as the fields are pushed into an array so the order should be respected.  The kind of behaviour you're seeing might make sense if they were in an object where order is not necessarily respected.  Will see if I can track this one down

**Comment by fourstacks** [comment]
@tanthammar I'm afraid I can't replicate this.  I copied your field config in your original message and the fields show up in the correct order in all views.  This is what I see on the detail (and index) views:

![image](https://user-images.githubusercontent.com/6280211/52169420-f2163a80-272f-11e9-8c55-49d36bab9afa.png)

If you can supply more information if you're still having issues then I'm happy to reopen this
