### ISSUE TITLE
Add options to number fields

### ISSUE THREAD

**Issue by tanthammar** [fourstacks/nova-repeatable-fields#12]
Is there an option to add max, min and step to the number field?
As of now it is impossible to add values like 0.5

**Comment by fourstacks** [comment]
@tanthammar - there is a PR for this #13 that should fix this issue for you once it's merged.  Hoping to get onto this over the weekend

**Comment by rk** [comment]
Looks like PR #13 is closed/deleted, and I could really use min/max and especially step properties for number fields. Is this something we need to implement and issue another PR for?

**Comment by fourstacks** [comment]
This is added in v1.2.0
