### ISSUE TITLE
Date field support

### ISSUE THREAD

**Issue by 3309** [fourstacks/nova-repeatable-fields#16]
Works great with current supported field. How can I add date field in the array? appreciated.

**Comment by Yelles** [comment]
would love that

**Comment by christianmarth** [comment]
Is there any way to implement this?

**Comment by fourstacks** [comment]
Happy to accept a PR for this if anyone can figure out a nice way of handling this that matches up with how the Nova date field does it's thing.  Not sure I'll have time to work on this myself for a while however
