### ISSUE TITLE
Repeatable relation field

### ISSUE THREAD

**Issue by willmkt** [fourstacks/nova-repeatable-fields#2]
Can this fiel be used with a relation?

Like if i have Order model and a OrderItens model?

Thanks.

**Comment by fourstacks** [comment]
Hi @willmkt, there is no support for this at the moment though it is a nice idea.  I'm planning on adding new field types over time so I'll give this some thought.

Just to be clear you're after having something like a select field that allows the user to choose a related item?

**Comment by willmkt** [comment]
Yes, i'm looking for a related select field.

Looking forward for the next features.

Thanks, and keep up the good work!

**Comment by julianpoma** [comment]
Hi John, thanks for this great package. Talking about relations, do you have plan to extend or create a similar package to store the "repeatable" fields in another table?

For example, we have an `invoice_table` and `invoice_items_table`. When creating an Invoice, I'd like to add as many items as I like, and each item should has its own row on the `invoice_items_table`, with a fk to the Invoice.

The invoice_items_table fieds are simple ones, like description and price

Thanks!

**Comment by fourstacks** [comment]
Hi @julianpoma, no problem - hope you find it useful!

I was mulling over whether it would be possible to hook into the save method that nova exposes `fillAttributeFromRequest `  - essentially allowing developers to define a callback function that takes the user input after which they are free to do whatever they want with it.

I built this package over the weekend as I needed this kind of repeater functionality for a project but I'm working with nova in a specific context (basically I'm using it as a CRM) and having the data save to a single field in the DB was just fine for my needs but I think it might be a bit limiting  in other projects.

I'll tinker around with the idea of creating a hook into which you can insert your own callbacks as I suspect that might be the most flexible approach.

**Comment by julianpoma** [comment]
@fourstacks Thanks for taking the time! I look foward what you can come up with ! I am also using nova as a full CRM!

**Comment by cerelli** [comment]
I'm interested in editing the package to save in an external table. I modified `fillAttributeFromRequest` but keeps asking me the attribute that naturally does not exist because it is external.
Any suggestions?

**Comment by julianpoma** [comment]
@cerelli I cannot help you, but there is a Laravel Official Discord now. Maybe you could ask for help, since this is a Nova functionality (there is a #Nova channel). Even Taylor is there.

Here is the invite link: https://discord.gg/mPZNm7A

**Comment by phuclh** [comment]
Look forward to seeing the relation field.
