### ISSUE TITLE
Using Repeatable field with a json attribute breaks loading saved data.

### ISSUE THREAD

**Issue by jeffreydevreede** [fourstacks/nova-repeatable-fields#23]
As you guys probably know, normally with a nova text field in combination with a json attribute you can do the following:

**Works:** 
```php
// In model:
protected $casts = ['content' => 'array'];

// In resource:
Text::make('Example title', 'content->exampleTitle')
```

But when I am trying to do this in combination with the `Repeatable` field it doesn't resolve the saved value, the rows I created are not being displayed, however the data seems to be as expected in the database.

**Broken:** 
```php
// In model:
protected $casts = ['content' => 'array'];

// In resource:
Repeater::make('USPs', 'content->usps')->addField([
    'label' => 'USP',
])
```

**Comment by rk** [comment]
This patch is really important to the app I'm building, as I've had to introduce 2 new fields just for my 2 repeaters (and more might be required). Maybe @fourstacks can merge this in as a patch release?

**Comment by fourstacks** [comment]
Added support via #24 in v1.1.0 - give it a whirl and let me know if there are any problems
