### ISSUE TITLE
Use `str_plural` on summaryLabel

### ISSUE THREAD

**Issue by jevets** [fourstacks/nova-repeatable-fields#3]
Should probably pass the `summaryLabel` through `str_plural()` when displayed, or maybe a user-defined callback or something.

<img width="533" alt="screen shot 2018-09-04 at 12 13 38 pm" src="https://user-images.githubusercontent.com/1187075/45043762-23cd8d00-b03c-11e8-8c9d-ff8af71cf9dc.png">

**Comment by fourstacks** [comment]
Hi @jevets - that's a good call - will add that to the to do list.  Thanks for the suggestion!
