### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by InfinityWebMe** [fourstacks/nova-repeatable-fields#30]
Hello,

have you plan to add a support of multi language ? 

Example : Im using spatie/laravel-translatable together with DigitalCloud/multilingual-nova

Thanks for your work ;)

**Comment by fourstacks** [comment]
@InfinityWebMe - I don't have any immediate plans but very happy to accept a PR for this if it's something like to see in the package.  Thanks!

**Comment by nemrutco** [comment]
I am also interested on this. But i believe it's something to do with spatie/laravel-translatable itself, From what i read about it, they don't want to change received type other then string. I am not sure if it's possible to manipulate to json string using observers.
