### ISSUE TITLE
[Feature Request] Allow groups in select options

### ISSUE THREAD

**Issue by sagaio** [fourstacks/nova-repeatable-fields#31]
Would it be possible to allow grouping of select options, just like the Nova Field Select?
```
Select::make('Size')->options([
    'MS' => ['label' => 'Small', 'group' => 'Men Sizes'],
    'MM' => ['label' => 'Medium', 'group' => 'Men Sizes'],
    'WS' => ['label' => 'Small', 'group' => 'Women Sizes'],
    'WM' => ['label' => 'Medium', 'group' => 'Women Sizes'],
])->displayUsingLabels()
```

**Comment by fourstacks** [comment]
@sagaio - nice idea - will see what I can do on this one.  Might not be able to get onto this quickly due to other commitments though so if you want to whip up a PR in the meantime I'd be happy to accept
