### ISSUE TITLE
i am getting an error when clicking on the add row button

### ISSUE THREAD

**Issue by jafar690** [fourstacks/nova-repeatable-fields#32]
on the create or edit page, i get the following error when i click on the `add row` button
![Screenshot from 2019-04-14 14-44-13](https://user-images.githubusercontent.com/17546030/56092366-ff843980-5ec3-11e9-9ca1-d4bbbba94d33.png)

laravel version: 5.7.28
nova version: 1.3.0

**Comment by curder** [comment]
The same issue, check your database relation filed's value and try to truncate it. And solve it. 
Maybe help for you, thanks.
