### ISSUE TITLE
[Feature Request] Integration with Maatwebsite - Laravel Nova Excel

### ISSUE THREAD

**Issue by stezani** [fourstacks/nova-repeatable-fields#33]
Hi! Thank you for your plugin. Is there a possibility to export some specific JSON fields to excel using the Laravel Nova Excel? For example, if i have 3 dogs with Name, Age, Race, i want to export only names, is it possible? Thank you again!

**Comment by fourstacks** [comment]
Hi @stezani - I think this is more a question for Nova Excel - the repeatable fields package just saves to a db column, nothing more, nothing less.  You can customise your nova exports fully I believe (see their docs: https://docs.laravel-excel.com/nova/1.0/exports/customizations.html#full-control) so I suggest you start there and ping the maintainers of that package a message if you get stuck.
