### ISSUE TITLE
support relationships

### ISSUE THREAD

**Issue by devmsh** [fourstacks/nova-repeatable-fields#4]
Thanks for the great package.

Any plan to support master details relationship? rather than a JSON field?

**Comment by fourstacks** [comment]
Hi @devmsh - could you elaborate a little bit?  I'm not sure I follow what you are after?

The idea of a relationship field was discussed in #2 and is something I'll be giving some thought to.  If your idea is different to this could you provide some more details on what you are trying to achieve?
