### ISSUE TITLE
How to populate data in edit form?

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [fourstacks/nova-repeatable-fields#42]
How I can populate the inserted data in the edit form, is there any option to specify that?

**Comment by mexoboy** [comment]
@PrafullaKumarSahu I found solution. You need set value for repeatable as json string. Is strange behaviour, but it's works. For example:
$repeatable->value = '[{"name": "Alex", "age": 26}, {"name": "John", "age": 38}]';
