### ISSUE TITLE
displayStackedForm not Working

### ISSUE THREAD

**Issue by jahid56** [fourstacks/nova-repeatable-fields#47]
My displayStackedForm option not working as expected
Here is my code 
`Repeater::make('Employees')
->addField([
	'label' => 'Full name',
	'name' => 'full_name',
	'type' => 'text',
	'placeholder' => 'Full Name',
])
->addField([
	'label' => 'ID No',
	'name' => 'id_no',
	'type' => 'text',
	'placeholder' => 'ID No',
])
->displayStackedForm()
->initialRows(1)->hideFromIndex(),`

But it doesnot show form in stacked way
![Screenshot_1](https://user-images.githubusercontent.com/18249715/64507915-c7134b00-d2fd-11e9-9284-1eb1a84d70af.png)
Didn't find where the problem was?

**Comment by fourstacks** [comment]
Hi @jahid56 - from the looks of your screenshot your field is stacked as expected (each field appears in a vertical stack rather than a horizontal row).  Closing this as it appears to be working as expected
