### ISSUE TITLE
Support nova fields 

### ISSUE THREAD

**Issue by dillingham** [fourstacks/nova-repeatable-fields#5]
I definitely think nova fields should be used. 
The package’s role is to repeat fields.
I expected to be able to use any field. 
Like using a toggle and a wysiwyg editor. 
I would open it up and offload that concern

**Comment by jsphpl** [comment]
Currently working on a PR for this

**Comment by doitrem** [comment]
> Currently working on a PR for this

when ?)

**Comment by fourstacks** [comment]
Hi all, whilst I like the idea of this I don't really have time to build this out just at the moment.  For now if might be worth looking at alternatives such as : https://novapackages.com/packages/64robots/nova-row

**Comment by doitrem** [comment]
> Привет всем, в то время как мне нравится идея этого, у меня на самом деле нет времени, чтобы построить это сейчас. Пока, если стоит взглянуть на альтернативы, такие как: https://novapackages.com/packages/64robots/nova-row

not working with image

**Comment by doitrem** [comment]
> Hi all, whilst I like the idea of this I don't really have time to build this out just at the moment. For now if might be worth looking at alternatives such as : https://novapackages.com/packages/64robots/nova-row

not working with image
The new line when adding photos changes the photo in the first field. All hope for you

**Comment by fourstacks** [comment]
Closing this for now as the field functions the way I'd originally envisaged - more than happy for someone to use it as a basis for building out a version that works with native Nova fields
