### ISSUE TITLE
Support for BelongsToMany fields

### ISSUE THREAD

**Issue by habibalkhabbaz** [fourstacks/nova-repeatable-fields#8]
Kindly add support for BelongsToMany fields.
It shows "Object of class stdClass could not be converted to string" when attaching.

**Comment by fourstacks** [comment]
@habibalkhabbaz - Sorry for such a slow reply.  I'm afraid native Nova fields are not currently supported by this package though relationship fields have been requested in other issues.  I'm closing this for now as I have no immediate plans to support this
